name: Test PROD Env

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installation
      run: yarn install
    - name: Build prod environment
      run: yarn build
    - name: Test prod environment
      run: |
        yarn test
      env:
        PROD: true

